### ISSUE TITLE
Count the Lone Ones

### ISSUE THREAD

**Issue by danielpaul** [Anishluke92/ProblemSolving#10]
Create a function which counts how many lone `1`s appear in a given number. Lone means the number doesn't appear twice or more in a row.

## Examples
```
count_lone_ones(101) ➞ 2

count_lone_ones(1191) ➞ 1

count_lone_ones(1111) ➞ 0

count_lone_ones(462) ➞ 0
```

## Notes
Tests will include positive whole numbers only.

**Comment by Anishluke92** [comment]
Algorithm 
1. Lets take two  numbes101 and 1191.
2. In these numbers we need to find the count of lone 1's.  which doesn't appear twice.
3. from 101, lets take the first number 1 compare it with next number 0 and 1 doesn't repeat twice so we can count + 1.
4. then we check the next number 1 with the previous number  0. we found another lone  1 so we increase the count +1. 
so in total the count would be 2. 
5 Lets take the next number 1191, First lets take first number 1 compare it with next number 1 and we found repetition, then we compare the next number 9  with the previous number 1 and we found a different number(non repeating number). 
6.To the last we compare the next number 1 with the previous number 9, then we found our first lone 1. we should then  increase the count +1. 
in total the count would be  1

**Comment by danielpaul** [comment]
@Anishluke92 in the algorithm, dont use specific examples. It should be generic enough that you can apply it to any number. Algorithms cannot be specific. You cannot give this algorithm to someone and ask them to follow your instructions for a new number they have not seen. Like how can I follow your instructions for the number 1231121931? There are no instructions I can follow from your algorithm to find out the lone numbers from this new number I have not seen.

 So something like this might be what it should look like:

1. Given a number, we go through each of the digits of the number from one end to the other. 
3. We keep track of how many ones we have seen that are alone in the number. 
4. When we are on one number, check if the number is a 1. 
5. If the number is a 1, check if the digit before or digit after this is not a 1. If there are no 1 beside it, count this as a lone 1. 
6. Repeat till you get to the end of the list.

**Comment by Anishluke92** [comment]
Sure, i will fix the algorithm now
