### ISSUE TITLE
Recursion: Length of a String

### ISSUE THREAD

**Issue by danielpaul** [Anishluke92/ProblemSolving#14]
Write a function that returns the length of a string. Make your function recursive.

Examples
```
length("apple") ➞ 5

length("make") ➞ 4

length("a") ➞ 1

length("") ➞ 0
```

Notes
Check the Resources tab for info on recursion.

**Comment by Anishluke92** [comment]
What do you mean by  make a function recursive ?

**Comment by danielpaul** [comment]
> What do you mean by make a function recursive ?

have a look at the differences between iterative methods and recursive methods. https://medium.com/backticks-tildes/iteration-vs-recursion-c2017a483890

So the recursive method is something that calls itself. So this is a bit of new thing that you possibly have not done yet that we need to learn. Some links that might help to understand the concept of recurssion: 

* https://medium.com/better-programming/how-to-write-recursion-in-3-steps-9d512189a94e
* https://www.geeksforgeeks.org/recursive-functions/
* https://books.trinket.io/thinkjava2/chapter8.html

**Comment by Anishluke92** [comment]
I will look into it !
