### ISSUE TITLE
Change Every Letter to the Next Letter

### ISSUE THREAD

**Issue by danielpaul** [Anishluke92/ProblemSolving#16]
Write a function that changes every letter to the next letter:

"a" becomes "b"
"b" becomes "c"
"d" becomes "e"
and so on ...

Examples
```
move("hello") ➞ "ifmmp"

move("bye") ➞ "czf"

move("welcome") ➞ "xfmdpnf"
```

Notes
There will be no z's in the tests.

**Comment by Anishluke92** [comment]
Algorithm: 
1. Given a word, Lets take the first letter and find the next letter of it according to the alphabetical order. 
2. Similarly do it for the rest of the letters of the word. 
3. Merge all the found alphabets as one word.
