### ISSUE TITLE
FizzBuzz

### ISSUE THREAD

**Issue by danielpaul** [Anishluke92/ProblemSolving#28]
Write a short program that prints each number from 1 to 100 on a new line. 

For each multiple of 3, print "Fizz" instead of the number. 

For each multiple of 5, print "Buzz" instead of the number. 

For numbers which are multiples of both 3 and 5, print "FizzBuzz" instead of the number.

**Comment by Anishluke92** [comment]
Algorithm:
1. Let take numbers from 1 to 100. 
2. Let's take the first number, and check if the number was a multiple of both 3 and 5 if so then we change the number to FizzBuzz.
3. If it was not a multiple of both, then lets  check the number if its a multiple of 3 alone if so we change that number to Fizz. Else lets check if that number is a multiple of 5  if so we change that number to Buzz.

**Comment by Anishluke92** [comment]
I have updated it !
