### ISSUE TITLE
Sort by Length

### ISSUE THREAD

**Issue by danielpaul** [Anishluke92/ProblemSolving#8]
Create a function that takes a string and returns a string ordered by the length of the words. From shortest to the longest word. If there are words with the same amount of letters, order them alphabetically.

## Examples
```
sort_by_length("Hello my friend") ➞ "my Hello friend"

sort_by_length("Have a wonderful day") ➞ "a day Have wonderful"

sort_by_length("My son loves pineapples") ➞ "My son loves pineapples"
```

## Notes
Punctuation (periods, commas, etc) belongs to the word in front of it.

**Comment by Anishluke92** [comment]
Algorithm:
1. Lets take a sentence, for example "Hello my dear world". And in that sentence we see that it consist of four words. 
2. Let take the first word and count its alphabets to get the word size. 
3. then lets do the same to rest of the words in that sentence. 
4. Now we got to know all the word size  in that sentence. Lets rearrange the sentence by  sorting the words by size in ascending order. example,
"my dear hello world"

**Comment by danielpaul** [comment]
@Anishluke92 no example should be in the algorithm. be generic instructions to apply to any input.

**Comment by Anishluke92** [comment]
Updated Algorithm

1.We have a sentence.
2.Take the first word from the sentence and then check word size by counting each alphabets in that word.
3.Similarly do that for all the words in that sentence.
4.Based on the word size we need to rearrange the sentence in ascending order. Example from the smallest word to Biggest word in size.
